services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: orla-tech
      POSTGRES_USER: orla-tech
      POSTGRES_PASSWORD: orla-tech
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: orla-tech@orla-tech.com
      PGADMIN_DEFAULT_PASSWORD: orla-tech
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - postgres_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge