services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: orla-tech
      POSTGRES_USER: orla-tech
      POSTGRES_PASSWORD: orla-tech
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: orla-tech@orla-tech.com
      PGADMIN_DEFAULT_PASSWORD: orla-tech
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal_network
    depends_on:
      - postgres

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: orla_tech_app
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orla-tech
      SPRING_DATASOURCE_USERNAME: orla-tech
      SPRING_DATASOURCE_PASSWORD: orla-tech
    ports:
      - "8081:80"
    networks:
      - internal_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  internal_network:
    driver: bridge
