# Server
server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/orla-tech
    username: orla-tech
    password: orla-tech
    hikari:
      minimumIdle: 2
      idleTimeout: 30000
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 120000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: orla_tech
        globally_quoted_identifiers: true
        format_sql: true
        hbm2ddl:
          create_namespaces: true
    show-sql: true

# Configurações do SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG